// <auto-generated />
namespace ReviewSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedcontentvaluesto1000andalterededittoalsoincludenewtextbox : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedcontentvaluesto1000andalterededittoalsoincludenewtextbox));
        
        string IMigrationMetadata.Id
        {
            get { return "201710300558003_changed content values to 1000 and altered edit to also include new text box"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
